<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OWASP Security Audit Report (2025)</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 2px solid #eee;
        }
        .category {
            margin-bottom: 30px;
            padding: 20px;
            border-radius: 8px;
            background-color: #f8f9fa;
        }
        .category-title {
            margin-top: 0;
            color: #2c3e50;
            font-size: 1.5em;
        }
        .check-item {
            margin: 10px 0;
            padding: 15px;
            border-radius: 4px;
            background-color: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .status {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-weight: bold;
            margin-right: 10px;
        }
        .status-success { background-color: #d4edda; color: #155724; }
        .status-warning { background-color: #fff3cd; color: #856404; }
        .status-error { background-color: #f8d7da; color: #721c24; }
        .status-pending { background-color: #e2e3e5; color: #383d41; }
        .timestamp {
            color: #6c757d;
            font-size: 0.9em;
            margin-top: 40px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>OWASP Security Audit Report (2025)</h1>
        <p>Generated on {{ date('d M Y H:i:s') }}</p>
    </div>

    @foreach($results as $category => $data)
        <div class="category">
            <h2 class="category-title">{{ strtoupper($category) }}</h2>
            
            @foreach($data['checks'] as $check => $result)
                <div class="check-item">
                    <span class="status status-{{ $result['status'] }}">
                        @switch($result['status'])
                            @case('success')
                                ✓
                                @break
                            @case('warning')
                                ⚠
                                @break
                            @case('error')
                                ✗
                                @break
                            @default
                                ?
                        @endswitch
                    </span>
                    <strong>{{ ucfirst(str_replace('_', ' ', $check)) }}</strong>
                    <p>{{ $result['message'] }}</p>
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="timestamp">
        <p>Report generated by <a href="https://github.com/dgtlss/owaspadvisor" target="_blank">OWASP Advisor</a></p>
    </div>
</body>
</html> 